# Generated by Django 3.2.5 on 2022-02-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listmodel',
            options={'verbose_name': 'Список дел', 'verbose_name_plural': 'Список дел'},
        ),
    ]
