# Generated by Django 3.2.5 on 2022-02-12 09:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_listmodel_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listmodel',
            unique_together={('name', 'user')},
        ),
    ]
